sudo: required
language: generic

services:
  - docker

before_install:
  - sudo apt-get -y install pass
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
  - docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t stephengrider/multi-nginx ./nginx
  # Log in to the docker CLI
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-nginx
